name: GitHub Monitor - Azure publish

on: [workflow_dispatch]

# TODO avoid job steps copy paste with composite actions

jobs: 
  publish_onlab:
    environment: onlab
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: "Run dotnet build"
        working-directory: github-monitor
        run: dotnet build --configuration Release --output ./output

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ahk-github-monitor
          package: "./github-monitor/output"
          publish-profile: ${{ secrets.GITHUBMONITOR_AZUREPUBLISHPROFILE }}
